language: node_js
node_js:
  - "8"
  - "10"
git:
  depth: 5
cache:
  directories:
    node_modules
install: npm install --save-dev
before_script:
  - npm install grunt-cli@0.1.13 -g
  - npm install grunt@0.4.5
  - npm install grunt-bump@0.7.0
  - npm install grunt-cli@0.1.13
  - npm install grunt-contrib-clean@0.6.0
  - npm install grunt-contrib-concat@0.5.1
  - npm install grunt-contrib-copy@0.8.2
  - npm install grunt-contrib-uglify@0.11.0
  - npm install grunt-contrib-watch@1.1.0
  - npm install grunt-jsbeautifier@0.2.10
  - npm install grunt-replace@0.11.0
  - npm install load-grunt-tasks@3.4.0
  - grunt
after_failure: npm install && grunt
matrix:
  fast_finish: true
